ninja-gold-app/config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get '/users/:id/:activity' => 'users#activity', :as => :activity
  get '/users/:id' => 'users#show', :as=>:user
  get '/users' => 'users#new', :as=>:newgame
  post '/users' => 'users#create'
  post '/users/:id' => 'users#get_gold'
  post '/users/:id/log' => 'users#get_log'

end

ninja-gold-app/app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :user
end

ninja-gold-app/app/models/user.rb
class User < ActiveRecord::Base
	def do_activity activity
		change = 0
		if activity == "hunt" then change= Random.rand(11) end #0,10
		if activity == "farm" then change= Random.rand(6)+2 end #2,7
		if activity == "mine" then change= Random.rand(3)+3 end #3,5
		if activity == "gamble" #-50,20 with pr(40) lose
			change = Random.rand(21)-Random.rand(25)
		end
		self.update(gold: self.gold+change)
		if change > 0
			evt = "You went to "+activity+" and gained "+change.to_s+" gold."
	    else
	    	evt = "You went to "+activity+" and lost "+change.abs.to_s+" gold."
	    end
	    Log.new(user_id: self.id, event:evt).save
	end
	def get_log
		Log.where(user_id: self.id)
	end
end

ninja-gold-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
protect_from_forgery with: :null_session
end

ninja-gold-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :xml, :json
  def new
    @user = User.new
  end
  def create
    @user = User.new(name:user_params[:name], gold:0)
    @user.save
    redirect_to @user
  end
  def show
    @user = User.find_by_id(params[:id])
  end

  def index
    @users = User.all
  end

  def activity #this handles user quests (hunt, farm, mine, gamble)
    user = User.find_by_id(params[:id])
    user.do_activity params[:activity]
  end

  def get_gold
    @user = User.find_by_id(params[:id])
    render :json => @user
  end
  def get_log
    user = User.find_by_id(params[:id])#the model must get the log
    render :json => user.get_log
  end

  private
    def user_params
      params.require(:user).permit(:name)
    end
end

ninja-gold-app/app/helpers/ninjas_helper.rb
module NinjasHelper
end

ninja-gold-app/app/helpers/numbers_helper.rb
module NumbersHelper
end

ninja-gold-app/app/helpers/users_helper.rb
module UsersHelper
end

ninja-gold-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinjaGoldApp</title>
  <script type="text/javascript" src="/jquery.js"></script>
  <script type="text/javascript" src="/redirect.js"></script>
  <link rel="stylesheet" type="text/css" href="/jason.css">  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ninja-gold-app/app/views/users/index.html.erb
<p>Welcome to ninja gold</p>
<%= link_to 'make a new game', newgame_path %>
<table>
  <tr>
    <th>Game</th>
    <th>Play</th>
  </tr>
<% @users.each do |user| %>
  <tr>
    <td>Game Number <%= user.id %></td>
    <td><%= link_to 'game link', user %></td>
  </tr>
<% end %>
</table>

ninja-gold-app/app/views/users/new.html.erb
<div id="wrapper">
	<h2>Create a Ninja</h2>
	<div id="hint"></div>
	<%= form_for(@user) do |f|%>
    <%= f.label :name, 'name of your ninja'%>
    <%= f.text_field :name %>
    <%= f.submit 'start'%>
	<% end %>
	<button onclick="go_back_to_index()" class="back_button">Back</button>
</div>

ninja-gold-app/app/views/users/show.html.erb
<div id="user_status">
	<span id="name"><%=@user.name %></span>
	<span id="count"><%=@user.gold%></span>
</div>
<div id="quests">
	<button id="hunt">Hunt</button>
	<button id="farm">Farm</button>
	<button id="mine">Mine</button>
	<button id="gamble">Gamble</button>
</div>
<div id="log" style="overflow:-moz-scrollbars-vertical;overflow-y:auto;"></div>
<button onclick="go_back_to_index()" class="back_button">Back</button>
<script type="text/javascript" src="/ninjagold.js"></script>